/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_woxiao_game_tv_JNITest */

#ifndef _Included_com_tinker_test_JNITest
#define _Included_com_tinker_test_JNITest
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_tinker_test_JNITest_fromJNIString
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_tinker_test_JNITest_fromJNIString2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
